sudo: required
language: node_js
node_js:
  - "9"
services:
  - docker
before_install:
  # login to docker registries (dockerhub + heroku)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
install:
  # install deps
  - yarn install
script:
  - yarn test
  - yarn build
  # build docker images
  - docker build -t template-shop:1.0 .
deploy:
  provider: script
  script:
    # push to dockerhub
    docker push belduque/template-shop;
  branch: master
