sudo: required
language: node_js
node_js:
  - "10"
services:
  - docker

before_install:
  # login to docker registries (dockerhub)
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

install:
  # install deps
  - yarn install

script:
  - yarn build
  # build docker images
  - docker build -t template-shop .
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag front $DOCKER_USER/front:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USER/front:$TRAVIS_BUILD_NUMBER
  - docker tag front $DOCKER_USER/front:latest
  - docker push $DOCKER_USER/front:latest
