sudo: required
language: node_js
node_js:
  - "8.10.0"
services:
  - docker

before_install:
  # login to docker registries (dockerhub)
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

install:
  # install deps
  - yarn install

script:
  - yarn build
  # build docker images
  - docker build -t belduque/template-shop .

deploy:
  provider: script
  script:
    # push to dockerhub
    docker push belduque/template-shop;
  on:
    branch: master
