sudo: required
language: node_js
node_js:
  - "12.10.0-alpine"
services:
  - docker
before_install:
  # login to docker registries (dockerhub + heroku)
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
install:
  # install deps
  - yarn install
script:
  - yarn build
  # build docker images
  - docker build -t template-shop:1.0 .
deploy:
  provider: script
  script:
    # push to dockerhub
    docker push belduque/template-shop;
  branch: master
