sudo: required

services:
  - docker

before_install:
  # login to docker registries (dockerhub + heroku)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
install:
  # install deps
  - yarn install
script:
  - yarn test
  - yarn build
